# A compose override, to be run via:
# docker compose -f compose.yaml -f compose.test.yaml run --rm api
services:
  api:
    command: test -timeout=5m -v -tags=e2e ./...
    restart: "no"
    healthcheck:
      test: []
