# A compose override, to be run via:
# docker compose -f compose.yaml -f compose.test.yaml run --rm api
services:
  api:
    build:
      target: build
    # Use .test.env instead of .env to ensure tests use MinIO configuration
    env_file: .test.env
    command: test -timeout=5m -v -tags=e2e ./...
    restart: "no"
    healthcheck:
      test: []
  
  s3:
    # Ensure MinIO service uses test credentials (matching .test.env)
    environment:
      MINIO_ROOT_USER: odm
      MINIO_ROOT_PASSWORD: somelongpassword

volumes:
  test-cache:
