apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scaleodm.fullname" . }}-config
  labels:
    {{- include "scaleodm.labels" . | nindent 4 }}
data:
  ODM_IMAGE: {{ .Values.config.odmImage | quote }}
  K8S_NAMESPACE: {{ .Release.Namespace | quote }}
