// Expose env var config vars, with defaults

package config

import (
	"cmp"
	"log"
	"os"
	"strconv"
	"strings"

	"github.com/hotosm/scaleodm/app/version"
)

func envBool(key string, fallback bool) bool {
	value := strings.TrimSpace(os.Getenv(key))
	if value == "" {
		return fallback
	}
	parsed, err := strconv.ParseBool(value)
	if err != nil {
		log.Printf("invalid boolean for %s=%q, using default %t", key, value, fallback)
		return fallback
	}
	return parsed
}

func envInt(key string, fallback int) int {
	value := strings.TrimSpace(os.Getenv(key))
	if value == "" {
		return fallback
	}
	parsed, err := strconv.Atoi(value)
	if err != nil {
		log.Printf("invalid integer for %s=%q, using default %d", key, value, fallback)
		return fallback
	}
	return parsed
}

func envFloat(key string, fallback float64) float64 {
	value := strings.TrimSpace(os.Getenv(key))
	if value == "" {
		return fallback
	}
	parsed, err := strconv.ParseFloat(value, 64)
	if err != nil {
		log.Printf("invalid float for %s=%q, using default %f", key, value, fallback)
		return fallback
	}
	return parsed
}

var SCALEODM_ODM_IMAGE = cmp.Or(
	os.Getenv("SCALEODM_ODM_IMAGE"),
	"ghcr.io/hotosm/odm:3.6.0",
)

var SCALEODM_DATABASE_URL = cmp.Or(
	os.Getenv("SCALEODM_DATABASE_URL"),
	"",
)

var KUBECONFIG_PATH = cmp.Or(
	os.Getenv("KUBECONFIG_PATH"),
	"", // leave empty if in-cluster
)

// K8S_NAMESPACE is the namespace where ScaleODM and its workflows run.
// Defaults to "default". In Helm deployments this is set to the release namespace.
var K8S_NAMESPACE = cmp.Or(
	os.Getenv("K8S_NAMESPACE"),
	"default",
)

var AWS_S3_ENDPOINT = cmp.Or(
	os.Getenv("AWS_S3_ENDPOINT"),
	"s3.amazonaws.com",
)
var AWS_ACCESS_KEY_ID = cmp.Or(
	os.Getenv("AWS_ACCESS_KEY_ID"),
	"",
)
var AWS_SECRET_ACCESS_KEY = cmp.Or(
	os.Getenv("AWS_SECRET_ACCESS_KEY"),
	"",
)
var AWS_DEFAULT_REGION = cmp.Or(
	strings.TrimSpace(os.Getenv("AWS_DEFAULT_REGION")),
	"us-east-1",
)

// AWS_S3_SECRET_NAME is the name of the unified runtime Kubernetes Secret
// (in the same namespace as ScaleODM) that workflow containers use for S3
// credentials via secretKeyRef. This same secret is also used by the API
// deployment for SCALEODM_DATABASE_URL and AWS_S3_ENDPOINT credentials.
// The secret must contain at least:
//   - AWS_ACCESS_KEY_ID
//   - AWS_SECRET_ACCESS_KEY
//
// AWS_DEFAULT_REGION defaults to us-east-1 at runtime when not provided.
var AWS_S3_SECRET_NAME = cmp.Or(
	os.Getenv("AWS_S3_SECRET_NAME"),
	"scaleodm-secrets",
)

var SCALEODM_ENFORCE_S3_ENDPOINT_ALLOWLIST = envBool("SCALEODM_ENFORCE_S3_ENDPOINT_ALLOWLIST", false)
var SCALEODM_ALLOWED_S3_ENDPOINTS = strings.TrimSpace(os.Getenv("SCALEODM_ALLOWED_S3_ENDPOINTS"))

// SCALEODM_ARGO_ARCHIVE_LOG_BUCKET names the S3 bucket where Argo's executor
// archives pod stdout (per-pod main.log objects under
// <bucket>/<namespace>/<workflow>/<pod>/main.log when archiveLogs is enabled
// in the chart). Empty disables the post-pod-GC log fallback - the UI/API
// will still serve live pod logs via the Kubernetes API during the
// workflow's TTL window, but won't have anywhere to read from afterward.
//
// Must match argo.artifactRepository.s3.bucket in the Helm values.
var SCALEODM_ARGO_ARCHIVE_LOG_BUCKET = strings.TrimSpace(os.Getenv("SCALEODM_ARGO_ARCHIVE_LOG_BUCKET"))

var SCALEODM_WORKFLOW_MISSING_GRACE_SECONDS = envInt("SCALEODM_WORKFLOW_MISSING_GRACE_SECONDS", 300)

// SCALEODM_RECONCILER_INTERVAL_SECONDS controls how often the background
// reconciler syncs live Argo workflow status into the DB. 30 s is short enough
// to catch completions well before the default Argo GC TTL (24 h for success,
// 7 days for failure), while the idle cost is just one cheap DB query per tick.
// Set to 0 or negative to use the default.
var SCALEODM_RECONCILER_INTERVAL_SECONDS = envInt("SCALEODM_RECONCILER_INTERVAL_SECONDS", 30)

var SCALEODM_SERVER_READ_HEADER_TIMEOUT_SECONDS = envInt("SCALEODM_SERVER_READ_HEADER_TIMEOUT_SECONDS", 10)
var SCALEODM_SERVER_READ_TIMEOUT_SECONDS = envInt("SCALEODM_SERVER_READ_TIMEOUT_SECONDS", 30)
var SCALEODM_SERVER_WRITE_TIMEOUT_SECONDS = envInt("SCALEODM_SERVER_WRITE_TIMEOUT_SECONDS", 300)
var SCALEODM_SERVER_IDLE_TIMEOUT_SECONDS = envInt("SCALEODM_SERVER_IDLE_TIMEOUT_SECONDS", 120)

var SCALEODM_READINESS_CHECK_S3 = envBool("SCALEODM_READINESS_CHECK_S3", false)
var SCALEODM_READINESS_S3_PROBE_PATH = strings.TrimSpace(os.Getenv("SCALEODM_READINESS_S3_PROBE_PATH"))
var SCALEODM_READINESS_TIMEOUT_SECONDS = envInt("SCALEODM_READINESS_TIMEOUT_SECONDS", 5)

var SCALEODM_UI_ENABLED = envBool("SCALEODM_UI_ENABLED", false)
var SCALEODM_UI_READONLY = envBool("SCALEODM_UI_READONLY", true)

var SCALEODM_OBSERVABILITY_ENABLED = envBool("SCALEODM_OBSERVABILITY_ENABLED", false)
var SCALEODM_OBSERVABILITY_SERVICE_NAME = cmp.Or(
	strings.TrimSpace(os.Getenv("SCALEODM_OBSERVABILITY_SERVICE_NAME")),
	"scaleodm",
)
var SCALEODM_OBSERVABILITY_SERVICE_VERSION = cmp.Or(
	strings.TrimSpace(os.Getenv("SCALEODM_OBSERVABILITY_SERVICE_VERSION")),
	version.Version,
)
var SCALEODM_OBSERVABILITY_OTLP_ENDPOINT = strings.TrimSpace(os.Getenv("SCALEODM_OBSERVABILITY_OTLP_ENDPOINT"))
var SCALEODM_OBSERVABILITY_OTLP_INSECURE = envBool("SCALEODM_OBSERVABILITY_OTLP_INSECURE", false)
var SCALEODM_OBSERVABILITY_METRICS_ENABLED = envBool("SCALEODM_OBSERVABILITY_METRICS_ENABLED", SCALEODM_OBSERVABILITY_ENABLED)
var SCALEODM_OBSERVABILITY_TRACES_ENABLED = envBool("SCALEODM_OBSERVABILITY_TRACES_ENABLED", SCALEODM_OBSERVABILITY_ENABLED)
var SCALEODM_OBSERVABILITY_TRACE_SAMPLE_RATIO = envFloat("SCALEODM_OBSERVABILITY_TRACE_SAMPLE_RATIO", 0.1)

var SCALEODM_WORKFLOW_ACTIVE_DEADLINE_SECONDS = envInt("SCALEODM_WORKFLOW_ACTIVE_DEADLINE_SECONDS", 21600)
var SCALEODM_WORKFLOW_WORKSPACE_MODE = cmp.Or(
	strings.TrimSpace(os.Getenv("SCALEODM_WORKFLOW_WORKSPACE_MODE")),
	"auto",
)
var SCALEODM_WORKFLOW_WORKSPACE_SIZE = cmp.Or(
	strings.TrimSpace(os.Getenv("SCALEODM_WORKFLOW_WORKSPACE_SIZE")),
	"30Gi",
)
var SCALEODM_WORKFLOW_WORKSPACE_STORAGE_CLASS = strings.TrimSpace(os.Getenv("SCALEODM_WORKFLOW_WORKSPACE_STORAGE_CLASS"))
var SCALEODM_WORKFLOW_WORKSPACE_ACCESS_MODE = cmp.Or(
	strings.TrimSpace(os.Getenv("SCALEODM_WORKFLOW_WORKSPACE_ACCESS_MODE")),
	"ReadWriteOnce",
)
var SCALEODM_WORKFLOW_WORKSPACE_DYNAMIC_SIZE_ENABLED = envBool("SCALEODM_WORKFLOW_WORKSPACE_DYNAMIC_SIZE_ENABLED", true)
var SCALEODM_WORKFLOW_WORKSPACE_DYNAMIC_SIZE_MAX_GIB = envFloat("SCALEODM_WORKFLOW_WORKSPACE_DYNAMIC_SIZE_MAX_GIB", 1024)
var SCALEODM_WORKFLOW_WORKSPACE_DYNAMIC_SIZE_FALLBACK_MB_PER_IMAGE = envFloat("SCALEODM_WORKFLOW_WORKSPACE_DYNAMIC_SIZE_FALLBACK_MB_PER_IMAGE", 20)
var SCALEODM_WORKFLOW_WORKSPACE_DYNAMIC_SIZE_FAST_ORTHO_MULTIPLIER = envFloat("SCALEODM_WORKFLOW_WORKSPACE_DYNAMIC_SIZE_FAST_ORTHO_MULTIPLIER", 3)
var SCALEODM_WORKFLOW_WORKSPACE_DYNAMIC_SIZE_FAST_ORTHO_MIN_GIB = envFloat("SCALEODM_WORKFLOW_WORKSPACE_DYNAMIC_SIZE_FAST_ORTHO_MIN_GIB", 30)
var SCALEODM_WORKFLOW_WORKSPACE_DYNAMIC_SIZE_STANDARD_MULTIPLIER = envFloat("SCALEODM_WORKFLOW_WORKSPACE_DYNAMIC_SIZE_STANDARD_MULTIPLIER", 6)
var SCALEODM_WORKFLOW_WORKSPACE_DYNAMIC_SIZE_STANDARD_MIN_GIB = envFloat("SCALEODM_WORKFLOW_WORKSPACE_DYNAMIC_SIZE_STANDARD_MIN_GIB", 50)
var SCALEODM_WORKFLOW_RETRY_LIMIT = envInt("SCALEODM_WORKFLOW_RETRY_LIMIT", 1)
var SCALEODM_WORKFLOW_RETRY_BACKOFF_DURATION = cmp.Or(
	os.Getenv("SCALEODM_WORKFLOW_RETRY_BACKOFF_DURATION"),
	"60s",
)
var SCALEODM_WORKFLOW_RETRY_BACKOFF_FACTOR = cmp.Or(
	os.Getenv("SCALEODM_WORKFLOW_RETRY_BACKOFF_FACTOR"),
	"2",
)
var SCALEODM_WORKFLOW_RETRY_BACKOFF_MAX_DURATION = cmp.Or(
	os.Getenv("SCALEODM_WORKFLOW_RETRY_BACKOFF_MAX_DURATION"),
	"6h",
)

// SCALEODM_WORKFLOW_RETRY_POLICY maps to Argo's retryStrategy.retryPolicy.
// Valid: Always | OnFailure | OnError | OnTransientError. See chart values.yaml.
var SCALEODM_WORKFLOW_RETRY_POLICY = cmp.Or(
	os.Getenv("SCALEODM_WORKFLOW_RETRY_POLICY"),
	"OnTransientError",
)
var SCALEODM_WORKFLOW_TTL_SUCCESS_SECONDS = envInt("SCALEODM_WORKFLOW_TTL_SUCCESS_SECONDS", 86400)
var SCALEODM_WORKFLOW_TTL_FAILURE_SECONDS = envInt("SCALEODM_WORKFLOW_TTL_FAILURE_SECONDS", 604800)
var SCALEODM_WORKFLOW_POD_GC_STRATEGY = cmp.Or(
	os.Getenv("SCALEODM_WORKFLOW_POD_GC_STRATEGY"),
	"OnWorkflowSuccess",
)
var SCALEODM_WORKFLOW_POD_GC_DELETE_DELAY_SECONDS = envInt("SCALEODM_WORKFLOW_POD_GC_DELETE_DELAY_SECONDS", 300)

// SCALEODM_WORKFLOW_CAPACITY_TYPE sets the default Karpenter node pool for
// workflow pods: "spot" (default, cheapest) or "on-demand" (stable, VIP).
// Individual workflow submissions can override this via the capacityType field.
var SCALEODM_WORKFLOW_CAPACITY_TYPE = cmp.Or(
	strings.TrimSpace(os.Getenv("SCALEODM_WORKFLOW_CAPACITY_TYPE")),
	"spot",
)

var SCALEODM_WORKFLOW_RESOURCES_DOWNLOAD_REQUEST_CPU = cmp.Or(os.Getenv("SCALEODM_WORKFLOW_RESOURCES_DOWNLOAD_REQUEST_CPU"), "500m")
var SCALEODM_WORKFLOW_RESOURCES_DOWNLOAD_REQUEST_MEMORY = cmp.Or(os.Getenv("SCALEODM_WORKFLOW_RESOURCES_DOWNLOAD_REQUEST_MEMORY"), "1Gi")
var SCALEODM_WORKFLOW_RESOURCES_DOWNLOAD_REQUEST_EPHEMERAL_STORAGE = cmp.Or(os.Getenv("SCALEODM_WORKFLOW_RESOURCES_DOWNLOAD_REQUEST_EPHEMERAL_STORAGE"), "2Gi")
var SCALEODM_WORKFLOW_RESOURCES_DOWNLOAD_LIMIT_CPU = cmp.Or(os.Getenv("SCALEODM_WORKFLOW_RESOURCES_DOWNLOAD_LIMIT_CPU"), "2")
var SCALEODM_WORKFLOW_RESOURCES_DOWNLOAD_LIMIT_MEMORY = cmp.Or(os.Getenv("SCALEODM_WORKFLOW_RESOURCES_DOWNLOAD_LIMIT_MEMORY"), "2Gi")
var SCALEODM_WORKFLOW_RESOURCES_DOWNLOAD_LIMIT_EPHEMERAL_STORAGE = cmp.Or(os.Getenv("SCALEODM_WORKFLOW_RESOURCES_DOWNLOAD_LIMIT_EPHEMERAL_STORAGE"), "6Gi")

var SCALEODM_WORKFLOW_RESOURCES_PROCESS_REQUEST_CPU = cmp.Or(os.Getenv("SCALEODM_WORKFLOW_RESOURCES_PROCESS_REQUEST_CPU"), "2000m")
var SCALEODM_WORKFLOW_RESOURCES_PROCESS_REQUEST_MEMORY = cmp.Or(os.Getenv("SCALEODM_WORKFLOW_RESOURCES_PROCESS_REQUEST_MEMORY"), "8Gi")
var SCALEODM_WORKFLOW_RESOURCES_PROCESS_REQUEST_EPHEMERAL_STORAGE = cmp.Or(os.Getenv("SCALEODM_WORKFLOW_RESOURCES_PROCESS_REQUEST_EPHEMERAL_STORAGE"), "20Gi")
var SCALEODM_WORKFLOW_RESOURCES_PROCESS_LIMIT_CPU = cmp.Or(os.Getenv("SCALEODM_WORKFLOW_RESOURCES_PROCESS_LIMIT_CPU"), "4000m")
var SCALEODM_WORKFLOW_RESOURCES_PROCESS_LIMIT_MEMORY = cmp.Or(os.Getenv("SCALEODM_WORKFLOW_RESOURCES_PROCESS_LIMIT_MEMORY"), "10Gi")
var SCALEODM_WORKFLOW_RESOURCES_PROCESS_LIMIT_EPHEMERAL_STORAGE = cmp.Or(os.Getenv("SCALEODM_WORKFLOW_RESOURCES_PROCESS_LIMIT_EPHEMERAL_STORAGE"), "30Gi")

var SCALEODM_WORKFLOW_RESOURCES_UPLOAD_REQUEST_CPU = cmp.Or(os.Getenv("SCALEODM_WORKFLOW_RESOURCES_UPLOAD_REQUEST_CPU"), "500m")
var SCALEODM_WORKFLOW_RESOURCES_UPLOAD_REQUEST_MEMORY = cmp.Or(os.Getenv("SCALEODM_WORKFLOW_RESOURCES_UPLOAD_REQUEST_MEMORY"), "1Gi")
var SCALEODM_WORKFLOW_RESOURCES_UPLOAD_REQUEST_EPHEMERAL_STORAGE = cmp.Or(os.Getenv("SCALEODM_WORKFLOW_RESOURCES_UPLOAD_REQUEST_EPHEMERAL_STORAGE"), "4Gi")
var SCALEODM_WORKFLOW_RESOURCES_UPLOAD_LIMIT_CPU = cmp.Or(os.Getenv("SCALEODM_WORKFLOW_RESOURCES_UPLOAD_LIMIT_CPU"), "2")
var SCALEODM_WORKFLOW_RESOURCES_UPLOAD_LIMIT_MEMORY = cmp.Or(os.Getenv("SCALEODM_WORKFLOW_RESOURCES_UPLOAD_LIMIT_MEMORY"), "2Gi")
var SCALEODM_WORKFLOW_RESOURCES_UPLOAD_LIMIT_EPHEMERAL_STORAGE = cmp.Or(os.Getenv("SCALEODM_WORKFLOW_RESOURCES_UPLOAD_LIMIT_EPHEMERAL_STORAGE"), "8Gi")

var SCALEODM_WORKFLOW_RESOURCES_CLEANUP_REQUEST_CPU = cmp.Or(os.Getenv("SCALEODM_WORKFLOW_RESOURCES_CLEANUP_REQUEST_CPU"), "250m")
var SCALEODM_WORKFLOW_RESOURCES_CLEANUP_REQUEST_MEMORY = cmp.Or(os.Getenv("SCALEODM_WORKFLOW_RESOURCES_CLEANUP_REQUEST_MEMORY"), "512Mi")
var SCALEODM_WORKFLOW_RESOURCES_CLEANUP_REQUEST_EPHEMERAL_STORAGE = cmp.Or(os.Getenv("SCALEODM_WORKFLOW_RESOURCES_CLEANUP_REQUEST_EPHEMERAL_STORAGE"), "1Gi")
var SCALEODM_WORKFLOW_RESOURCES_CLEANUP_LIMIT_CPU = cmp.Or(os.Getenv("SCALEODM_WORKFLOW_RESOURCES_CLEANUP_LIMIT_CPU"), "1")
var SCALEODM_WORKFLOW_RESOURCES_CLEANUP_LIMIT_MEMORY = cmp.Or(os.Getenv("SCALEODM_WORKFLOW_RESOURCES_CLEANUP_LIMIT_MEMORY"), "1Gi")
var SCALEODM_WORKFLOW_RESOURCES_CLEANUP_LIMIT_EPHEMERAL_STORAGE = cmp.Or(os.Getenv("SCALEODM_WORKFLOW_RESOURCES_CLEANUP_LIMIT_EPHEMERAL_STORAGE"), "2Gi")

var SCALEODM_PROCESS_MEMORY_LIMIT_MARGIN_PERCENT = envFloat("SCALEODM_PROCESS_MEMORY_LIMIT_MARGIN_PERCENT", 20)
var SCALEODM_PROCESS_MEMORY_MIN_GIB = envFloat("SCALEODM_PROCESS_MEMORY_MIN_GIB", 4)
var SCALEODM_PROCESS_MEMORY_MAX_GIB = envFloat("SCALEODM_PROCESS_MEMORY_MAX_GIB", 256)

// ODM process sizing is primarily RAM-driven; CPU does not scale linearly for
// the largest jobs and high requests can leave pods unschedulable. The default
// is 1 requested core per 8GiB estimated RAM, with limits controlled below.
var SCALEODM_PROCESS_CPU_PER_GIB = envFloat("SCALEODM_PROCESS_CPU_PER_GIB", 0.125)
var SCALEODM_PROCESS_CPU_LIMIT_MULTIPLIER = envFloat("SCALEODM_PROCESS_CPU_LIMIT_MULTIPLIER", 1.5)
var SCALEODM_PROCESS_EPHEMERAL_GIB_PER_GIB_RAM = envFloat("SCALEODM_PROCESS_EPHEMERAL_GIB_PER_GIB_RAM", 1)
var SCALEODM_PROCESS_EPHEMERAL_LIMIT_MULTIPLIER = envFloat("SCALEODM_PROCESS_EPHEMERAL_LIMIT_MULTIPLIER", 1.2)
var SCALEODM_PROCESS_FAST_ORTHO_MEMORY_MULTIPLIER = envFloat("SCALEODM_PROCESS_FAST_ORTHO_MEMORY_MULTIPLIER", 0.5)
var SCALEODM_PROCESS_DSM_DTM_MEMORY_MULTIPLIER = envFloat("SCALEODM_PROCESS_DSM_DTM_MEMORY_MULTIPLIER", 1.5)

func ValidateEnv() {
	required := []struct {
		val  string
		name string
	}{
		{SCALEODM_DATABASE_URL, "SCALEODM_DATABASE_URL"},
		{AWS_S3_ENDPOINT, "AWS_S3_ENDPOINT"},
		{AWS_ACCESS_KEY_ID, "AWS_ACCESS_KEY_ID"},
		{AWS_SECRET_ACCESS_KEY, "AWS_SECRET_ACCESS_KEY"},
	}

	for _, envVar := range required {
		if envVar.val == "" {
			log.Fatalf("%s is required", envVar.name)
		}
	}
}
